### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by samsonasik** [crysalead/jit#2]
Hi,
Any chance to have documentation for its usage? Thanks ;)

**Comment by jails** [comment]
This library has been designed specifically for Kahlan and it's proned to changes. Especially if [this extention](https://wiki.php.net/rfc/parser-extension-api) go out.

If you need a PHP parser, [this library](https://github.com/nikic/PHP-Parser) will be probably more suitable for you needs.

And for the `Interceptor` class, its behavior is somehow trivial, it's a simple proxy applied on top of the composer autoloader. [The specs](https://github.com/crysalead/jit/blob/master/spec/jit/InterceptorSpec.php) should give you a good overview of its API

**Comment by samsonasik** [comment]
thank you ;)
